# File: .github/workflows/repo-sync.yml
name: All_Scripts-🔄自动同步🔄
on:
  schedule:
    - cron: '20 11 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: repo-sync
jobs:
  repo-sync:
    env:
      PAT: ${{ github.event.client_payload.PAT || secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} # 我自己同步到gitee使用，其他人可忽略
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: lxk0301-🔄自动同步🔄
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://gitee.com/lxk0301/jd_scripts.git"
          source_branch: "master"
          destination_branch: "lxk0301"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}
      - name: ziye66666-🔄自动同步🔄
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/ziye66666/JavaScript.git"
          source_branch: "main"
          destination_branch: "ziye66666"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}
      - name: ZhiYi-N-🔄自动同步🔄
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/ZhiYi-N/Private-Script.git"
          source_branch: "master"
          destination_branch: "ZhiYi-N"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}
